version: '3'

services:
  app:
    build: ./app
    container_name: 'apache'
    depends_on:
      - db
    volumes:
      - ../src:/var/www/html
    ports:
      - 80:80
  db:
    build: ./db
    container_name: 'db'
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306